---
- name: Adding Java PPA repo
  apt_repository:
    repo: ppa:webupd8team/java

- name: Automatically accepting the Oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Installing Java 8
  apt:
    name: oracle-java8-installer
    state: present
    update_cache: yes