---
- name: Download binaries for Gitlab-runner
  get_url: 
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    dest: /usr/local/bin/gitlab-runner
  
- name: Give it permissions to execute
  file:
    path: /usr/local/bin/gitlab-runner
    mode: +x
  
- name: Create a GitLab CI user
  user:
    name: gitlab-runner
    comment: GitLab Runner
    shell: /bin/bash
    create_home: true

- name: Install gitlab-runner
  command: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
  
- name: Install and run as service
  command: gitlab-runner start