---
- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Update apt repository
  apt:
    update_cache: yes
  when: (gitlab_file.stat.exists == false)

- name: Install the necessary dependencies
  package: name={{ item }} state=present
  with_items:
    - curl
    - openssh-server
    - ca-certificates
  when: (gitlab_file.stat.exists == false)

- name: Download GitLab repository installation script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
    dest: /tmp/gitlab_install_repository.sh
  when: (gitlab_file.stat.exists == false)

- name: Install GitLab package repository
  shell: bash /tmp/gitlab_install_repository.sh
  when: (gitlab_file.stat.exists == false)

- name: Install GitLab
  package: name=gitlab-ee state=present
  environment:
    EXTERNAL_URL: "http://10.0.15.11"
  register: shell_result
  when: (gitlab_file.stat.exists == false)

# debug can be removed
- debug:
    var: shell_result.stdout_lines